#!/bin/sh

currentDir=`dirname $0`
basePath="${currentDir}/../.."

projectName="kd-project-01"
region="europe-west2"
bucketBasePath="gs://kdtestbucket"
dataType="SAMPLERECORD"
jarPath="${basePath}/dataflowsamplecore/target/dataflowsamplecore-1.0.0-bundle.jar"
inputPath="${bucketBasePath}/output/avro_conversion"
outputDir="${bucketBasePath}/output/avrogroup_conversion"
outputPath="${outputDir}/result"
jobName="groupavroconversion-${dataType}-`date +%Y%m%d%H%M%S`"
stagingLocation="${bucketBasePath}/staging/${jobName}"

gsutil rm -r ${outputDir}

#echo "Running avro conversion first...."
#sh ${currentDir}/avroconversion-run-gcp
#echo "Avro conversion finished...."

java -cp ${jarPath} dataflowsample.main.GroupByKeySampleMain \
  --runner=DataflowRunner \
  --project=${projectName} \
  --region=${region} \
  --stagingLocation=${stagingLocation} \
  --jobName="${jobName}" \
  --input="${inputPath}" \
  --datatype="${dataType}" \
  --output="${outputPath}"

gsutil rm -r ${stagingLocation}